// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omocieeenuuvnuizplgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tb2NpZWVlbnV1dm51aXpwbGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MjAzNjgsImV4cCI6MjA2Njk5NjM2OH0.geqaNEmjT3uuGzZW5zvXC8dtcb0BGGu-07rHZGpud_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});